config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:index] do
    resources :shopping_list, only: [:index]
    resources :foods, only: [:index, :create, :new, :destroy]
    resources :recipes, only: [:index, :show, :create, :destroy] do
      resources :recipe_foods, only: [:create, :destroy]
    end
  end
  resources :public_recipes, only: [:index]
  resources :recipes, only: [:show] do
    resources :recipe_foods, only: [:create, :destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Recipe, public: true
    return unless user.present?

    can :manage, Recipe, user_id: user.id
    can :manage, RecipeFood, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/recipes_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :foods

  def recipes_from_user
    recipes.order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.where(user_id: current_user.id)
  end

  def new
    @user = current_user
    @food = Food.new
    respond_to do |format|
      format.html { render :new }
    end
  end

  def create
    @food = current_user.foods.new(food_params)

    respond_to do |format|
      format.html do
        if @food.save
          flash[:success] = 'Food was successfully created.'
          redirect_to user_foods_path
        else
          flash[:error] = 'Food was not created.'
          render :new
        end
      end
    end
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to user_foods_path(current_user.id), notice: 'Food was successfully deleted.'
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.includes(:user).includes(recipe_foods: [:food]).where(public: true)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def index
    @foods = @user.foods
    p 'test'
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new(recipe_food_params)
    if @recipe_food.save
      flash[:notice] = 'The food has been added.'
      redirect_to [@recipe.user, @recipe]
    else
      redirect_to [@recipe.user, @recipe]
      flash[:alert] = 'Sorry, we failed to add this food'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    respond_to do |format|
      format.html { redirect_to [@recipe.user, @recipe], notice: 'Ingredient was successfully deleted.' }
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:foods_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource

  def index
    @user = current_user
    @recipes = @user.recipes
  end

  def show
    @user = current_user
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
    @foods = @user.foods
    @recipe_foods = @recipe.recipe_foods.includes(:food)
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      flash[:notice] = 'Your recipe has been created.'
      redirect_to [@recipe.user, @recipe]
    else
      redirect_to [:new_user_recipe]
      flash[:alert] = 'Sorry, we failed to create your recipe'
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    respond_to do |format|
      format.html { redirect_to [current_user, :recipes], notice: 'Recipe was successfully deleted.' }
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    @user = current_user
    @recipes = @user.recipes_from_user
    @foods = @user.foods

    total_cost_of_recipe(@recipes)
    total_items_for_recipe(@recipes)
  end

  def total_cost_of_recipe(recipes)
    0 unless recipes.any?
    @total_cost = 0
    recipes.each do |recipe|
      recipe.recipe_foods.each do |recipe_food|
        @total_cost += recipe_food.food.price * recipe_food.quantity
      end
    end
    @total_cost
  end

  def total_items_for_recipe(recipes)
    0 unless recipes.any?
    @total_items = 0
    recipes.each do |recipe|
      @total_items += recipe.recipe_foods.count
    end
    @total_items
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
  def get_food_sum(public_recipe)
    recipe_foods = public_recipe.recipe_foods
    count = 0
    recipe_foods.each do |f|
      count += f.quantity * f.food.price
    end
    count
  end
end

app/helpers/recipe_food_helper.rb
module RecipeFoodHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/foods/index.html.erb
<section class="foods">
  <h1>Foods</h1>

  <div class="button-container">
    <div class="add-food-button">
      <%= link_to "Add food", new_user_food_path %>
    </div>
  </div>

  <table cellspacing="0">
    <thead>
      <tr>
        <th>Name</th>
        <th>Measurement unit</th>
        <th>Unit price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= food.price %>$</td>
          <td>
            <%= button_to "Destroy", user_food_path(current_user.id, food.id), method: :delete%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</section>

app/views/foods/new.html.erb
<section class="show-posts">
<h1>Add food</h1>
  <div class="new-food-form">
    <%= form_with model: @food, url: user_foods_path, method: :post, local: true, class:"new-food" do |f| %>
    <div class="flex-label">
      <%= f.label "Food name" %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="flex-label">
      <%= f.label :measurement_unit %>
      <%= f.text_field :measurement_unit, class: 'form-control' %>
    </div>
    <div class="flex-label">
      <%= f.label "Unit price" %>
      <%= f.number_field :price, class: 'form-control', min: 1, max: 10000 %>
    </div>
    <div>
      <%= f.submit 'Create new food'%>
    </div>
    <%end%>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<header>
  <%if user_signed_in?%>
    <nav class="navbar">
      <ul class="nav-list">
        <li><%= link_to "Foods", [current_user, :foods] %></li>
        <li><%= link_to "Recipes", [current_user, :recipes] %></li>
        <li><%= link_to "Public Recipes", public_recipes_path %></li>
        <li><%= link_to "Shopping List", user_shopping_list_index_path(current_user.id) %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :post %></li>
      </ul>
    </nav>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/public_recipes/_public_recipe.html.erb
<%= link_to recipe_path(public_recipe.id), class: 'recipe-link' do %>
<li class="recipe">
  <div class="left-recipe-container">
    <h2><%=public_recipe.name %></h2>
    <h3>by <%= public_recipe.user.name %> <h3>
  </div>
  <div class="recipe-items">
    <p>Total food items: <%=public_recipe.recipe_foods.length %>
    <p>Total price: <%= get_food_sum(public_recipe) %>
  </div>
</li>
<% end %>

app/views/public_recipes/index.html.erb
<div class="public-recipes-container">
  <h2>Public recipes</h2>
  <%= render partial: "public_recipe", collection: @public_recipes %>
</div>

app/views/recipe_foods/_add_ingredient.html.erb
<div id="openAdd" class="add-modal">
  <%= form_with scope: :recipe_food, url: [@recipe, :recipe_foods], class: 'add-recipe-form' do |f|%>
    <h2>Add a new food to your recipe</h2>
    <a href="#close" title="Close" class="close">X</a>
    <%= f.select :food_id, @foods.collect { |food| [food.name, food.id] } %>
    <div class="recipe-times">
      <%= f.label :quantity %>
      <%= f.number_field :quantity %>
    </div>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/recipe_foods/_recipe_food.html.erb
<tr>
  <td><%= recipe_food.food.name %></td>
  <td><%= recipe_food.quantity || 0 %> <%= recipe_food.food.measurement_unit %></td>
  <td><%= recipe_food.food.price %>$</td>
  <% if can? :manage, @recipe %>
  <td><a href="#">MODIFY</a> <%= button_to 'REMOVE',  [@recipe, recipe_food], method: :delete, class: 'recipe-remove-btn'%></td>
  <% end %>
</tr>

app/views/recipes/_recipe.html.erb
<%= link_to [current_user, recipe], class: 'recipe-link' do %>
<li class="recipe">
  <div class="left-recipe-container">
    <h2><%= recipe.name %></h2>
    <% if can? :destroy, recipe %><%= button_to 'REMOVE', [current_user, recipe], method: :delete, class: 'recipe-remove-btn'%><% end %>
  </div>
  <div class="recipe-description">
    <%= recipe.description.truncate(100, separator: ' ') %>
  </div>
</li>
<% end %>

app/views/recipes/index.html.erb
<ul class="recipe-container">
<% if can? :manage, Recipe %>
  <a class='recipe-add' href="#openAdd">Add recipe</a>
  <div id="openAdd" class="add-modal">
    <%= form_with scope: :recipe, class: 'add-recipe-form' do |f|%>
      <h2>Add new recipe!</h2>
      <a href="#close" title="Close" class="close">X</a>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="description">
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>
      <div class="recipe-times">
        <%= f.label :preparation_time %>
        <%= f.number_field :preparation_time %> minutes
      </div>
      <div class="recipe-times">
        <%= f.label :cooking_time %>
        <%= f.number_field :cooking_time %> minutes
      </div>
      <div class="recipe-checkbox">
        Public
        <label class="switch">
        <%= f.check_box :public, class: 'form-check-input' %>
        <span class="slider round"></span>
        </label>
      </div>
      <%= f.submit "Submit" %>
<% end %>
</div>
 <%= render @recipes %>
 <% end %>
</ul>

app/views/recipes/show.html.erb
<% if can? :read, @recipe %>
<div class="show-recipe-container">
  <h2><%= @recipe.name %></h2>
  <div class="recipe-prep-and-public">
    <p>Preparation time: <%= @recipe.preparation_time %> minutes</p>
    <div class="recipe-checkbox">
      Public
      <label class="switch">
        <% if @recipe.public %>
        <input type="checkbox" checked disabled>
        <% else %>
        <input type="checkbox" disabled>
        <%end%>
        <span class="slider round" checked></span>
      </label>
    </div>
  </div>
  <p>Cooking time: <%= @recipe.cooking_time %> minutes</p>
  <p><%= @recipe.description %></p>
  <% if can? :manage, @recipe %>
  <a class='recipe-add-ingredient' href="#openAdd">Add ingredient</a>
  <%= render 'recipe_foods/add_ingredient' %>
  <% end %>
</div>
<table class="recipe-foods-table">
  <tr>
    <th>Food</th>
    <th>Quantity</th>
    <th>Value</th>
    <% if can? :manage, @recipe %><th>Actions</th><% end %>
  </tr>
  <%= render @recipe_foods %>
</table>
<% end %>

app/views/shopping_list/index.html.erb
<section class="shopping-list">
  <h1 class="shop-header">Shopping List</h1>
  <h3 class="items-to-buy">Total items to buy:<%=@total_items%></h3>
  <table cellspacing="0" class="shop-table">
    <thead>
      <tr class="headers">
        <th>Recipe name</th>
        <th>Food</th>
        <th>Quantity</th>
        <th>Total Price</th>
      </tr>
    </thead>
    <tbody>
      <% @recipes.each do |recipe| %>
          <% recipe.recipe_foods.each do |recipe_food| %>
        <tr class="food-info">
          <td><%= recipe_food.recipe.name %></td>
          <td><%= recipe_food.food.name %></td>
          <td><%= recipe_food.quantity %></td>
          <td><%= recipe_food.food.price * recipe_food.quantity %>$</td>
        </tr>
        <%end%>
      <% end %>
      <tr>
        <td colspan="4" class="total-cost">
          Total cost: <%= @total_cost%>$
        </td>
      </tr>
    </tbody>
  </table>

</section>

app/views/users/index.html.erb
Welcome to the Recipe App!
Please use the navigation bar to navigate through the app.